name: My First Workflow

on: push #on: [push, fork]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

          - name: Action - Checkout
            uses: actions/checkout@v4

          - name: List and Read File
            run: |
              echo "Welcome to my first workflow!"
              ls -ltra
              cat README.md

          - name: Generate ASCII Work
            run: cowsay -f dragon "Run for cows, I am a DRAGON...RAWR" >> dragon.txt

        #   - name: List of Files
        #     run: ls

        #   - name: View File Content
        #     run: cat README.md