name: My First Workflow

on: push #on: [push, fork]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

          - name: Action - Checkout
            uses: actions/checkout@v4

          - name: Welcome Message
            run: echo "Welcome to my first workflow!"

          - name: List of Files
            run: ls

          - name: View File Content
            run: cat README.md