name: Generate ASCII

on: push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: List Files
            run: |
              ls -ltra
              chmod +x ./.github/workflows/generateascii.sh
              pwd
              ls -ltra
              
          - name: ASCII Cowsay Program
            run: |
              ls -ltra
              ./.github/workflows/generateascii.sh
        #   - name: Install Cowsay Program
        #     run: sudo apt-get install cowsay -y
            
        #   - name: Execute Cowsay CMD
        #     run: cowsay -f dragon "Run for cows, I am a DRAGON...RAWR" >> dragon.txt

        #   - name: Test File.txt
        #     run: grep -i "dragon" dragon.txt

        #   - name: Read File
        #     run: cat dragon.txt

        #  - name: List Repo Files
        #    run: ls -ltra