name: Multi Stage Job Workflow
on: push

jobs: 
    deploy_job1: 
        runs-on: ubuntu-latest

        steps:
          - name: Install Cowsay Program
            run: sudo apt-get install cowsay -y

          - name: Execute Cowsay CMD
            run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

          - name: Sleep for 10 seconds
            run: sleep 10

          - name: Upload Artifact
            uses: actions/upload-artifact@v4
            with:
                name: dragon-file
                path: dragon.txt
    
    test_job2:
        needs: deploy_job1
        runs-on: ubuntu-latest

        steps: 

          - name: Download Artifact
            uses: actions/download-artifact@v4
            with:
                name: dragon-file
                
          - name: Test the dragon file.
            run: grep -i "dragon" dragon.txt

          - name: Sleep for 10 seconds
            run: sleep 10

    deploy_job3:
        needs: test_job2
        runs-on: ubuntu-latest
        
        steps:
          - name: Download Artifact
            uses: actions/download-artifact@v4
            with:
                name: dragon-file

          - name: Deploy the file and check it's content
            run: cat dragon.txt



